# Generated by Django 3.1.7 on 2021-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('urlPelicula', models.URLField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('año', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('reparto', models.CharField(max_length=50)),
                ('urlPortada', models.URLField(max_length=100)),
                ('valoracion', models.CharField(max_length=50)),
            ],
        ),
    ]
