# Generated by Django 3.1.7 on 2021-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappVideoClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='urlPelicula',
            field=models.CharField(max_length=100),
        ),
    ]
